env:
  browser: true
  es6: true
extends:
  - 'plugin:react/recommended'
  - airbnb
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - eslint-plugin-react-hooks
rules:
  semi: ["error", "never"]
  comma-dangle: ["error", "never"]
  brace-style: ["error", "stroustrup", { "allowSingleLine": true }]
  no-plusplus: "off"
  space-before-function-paren: ["error", {"anonymous": "always", "named": "never", "asyncArrow": "always"}]
  object-curly-newline: ["error", { "ImportDeclaration": "never", "ExportDeclaration": "never" }]
  no-empty: ["error", { "allowEmptyCatch": true }]
  operator-linebreak: ["error", "after"]
  curly: ["error", "multi"]
  no-use-before-define: "off"
  react/jsx-filename-extension: "off"
  react-hooks/rules-of-hooks: "error"
  react-hooks/exhaustive-deps: "warn"
  no-eval: "off"
